import type { AppData } from './types';

const d = (offset: number) => {
  const dt = new Date();
  dt.setDate(dt.getDate() - offset);
  return dt.toISOString().split('T')[0];
};

export function getDefaultData(): AppData {
  return {
    subjects: [
      {
        id: 's1', name: 'Artificial Intelligence', category: 'bca',
        description: 'BCA semester AI course covering ML basics, search algorithms, and knowledge representation',
        startDate: '2025-01-15', targetDate: '2025-06-30', progress: 55,
        status: 'in-progress', notes: 'Focus on decision trees and neural networks next', timeSpent: 18,
      },
      {
        id: 's2', name: 'Graph Theory', category: 'bca',
        description: 'Mathematical structures used to model pairwise relations between objects',
        startDate: '2025-01-15', targetDate: '2025-06-30', progress: 40,
        status: 'in-progress', notes: 'Completed Eulerian and Hamiltonian paths', timeSpent: 10,
      },
      {
        id: 's3', name: 'Data Warehousing & Mining', category: 'bca',
        description: 'Concepts of OLAP, ETL processes, and mining algorithms including clustering',
        startDate: '2025-01-15', targetDate: '2025-06-30', progress: 35,
        status: 'in-progress', notes: '', timeSpent: 8,
      },
      {
        id: 's4', name: 'MERN Backend', category: 'bca',
        description: 'Node.js, Express, MongoDB backend development for full-stack applications',
        startDate: '2025-01-15', targetDate: '2025-06-30', progress: 70,
        status: 'in-progress', notes: 'Completed REST APIs, working on JWT auth', timeSpent: 25,
      },
      {
        id: 's5', name: 'AI Lab', category: 'bca',
        description: 'Practical AI experiments and algorithm implementations',
        startDate: '2025-01-15', targetDate: '2025-06-30', progress: 75,
        status: 'in-progress', notes: 'Labs 1–6 completed', timeSpent: 15,
      },
      {
        id: 's6', name: 'Data Mining Lab', category: 'bca',
        description: 'Hands-on data mining projects using Weka and Python',
        startDate: '2025-01-15', targetDate: '2025-06-30', progress: 50,
        status: 'in-progress', notes: 'Association rule mining done', timeSpent: 12,
      },
      {
        id: 's7', name: 'Python Fundamentals', category: 'datascience',
        description: 'Core Python programming for data science including OOP and functional patterns',
        startDate: '2025-02-01', targetDate: '2025-04-30', progress: 85,
        status: 'in-progress', notes: 'Completed loops and conditionals, working on functions', timeSpent: 30,
      },
      {
        id: 's8', name: 'NumPy & Pandas', category: 'datascience',
        description: 'Data manipulation and numerical computing with NumPy arrays and Pandas DataFrames',
        startDate: '2025-04-01', targetDate: '2025-06-30', progress: 30,
        status: 'in-progress', notes: 'Started NumPy basics', timeSpent: 8,
      },
      {
        id: 's9', name: 'Statistics for Data Science', category: 'mathematics',
        description: 'Probability, descriptive and inferential statistics for ML applications',
        startDate: '2025-02-01', targetDate: '2025-07-31', progress: 45,
        status: 'in-progress', notes: 'Completed mean, median, mode, std dev', timeSpent: 14,
      },
      {
        id: 's10', name: 'Linear Algebra', category: 'mathematics',
        description: 'Vectors, matrices, eigenvalues, and their applications in ML',
        startDate: '2025-03-01', targetDate: '2025-08-31', progress: 20,
        status: 'not-started', notes: '', timeSpent: 4,
      },
      {
        id: 's11', name: 'IELTS Preparation', category: 'language',
        description: 'IELTS academic test preparation targeting Band 7.0+',
        startDate: '2025-03-01', targetDate: '2025-09-30', progress: 25,
        status: 'in-progress', notes: 'Focus on Reading and Writing tasks', timeSpent: 10,
      },
      {
        id: 's12', name: 'Google Data Analytics Certificate', category: 'certifications',
        description: 'Google Professional Data Analytics Certificate on Coursera',
        startDate: '2025-04-01', targetDate: '2025-10-31', progress: 30,
        status: 'in-progress', notes: 'Completed first 2 courses', timeSpent: 15,
      },
    ],
    roadmapItems: [
      { id: 'r1', title: 'Artificial Intelligence', category: 'BCA Subjects', completed: false, notes: '', order: 1 },
      { id: 'r2', title: 'Graph Theory', category: 'BCA Subjects', completed: false, notes: '', order: 2 },
      { id: 'r3', title: 'Data Warehousing & Mining', category: 'BCA Subjects', completed: false, notes: '', order: 3 },
      { id: 'r4', title: 'MERN Backend', category: 'BCA Subjects', completed: false, notes: '', order: 4 },
      { id: 'r5', title: 'AI Lab', category: 'BCA Subjects', completed: true, notes: 'Labs 1–6 done', order: 5 },
      { id: 'r6', title: 'Data Mining Lab', category: 'BCA Subjects', completed: false, notes: '', order: 6 },
      { id: 'r7', title: 'Python Fundamentals', category: 'Data Science', month: 'Month 1', completed: true, notes: '', order: 7 },
      { id: 'r8', title: 'Variables & Data Types', category: 'Data Science', month: 'Month 1', completed: true, notes: '', order: 8 },
      { id: 'r9', title: 'Input/Output Operations', category: 'Data Science', month: 'Month 1', completed: true, notes: '', order: 9 },
      { id: 'r10', title: 'If-Else Conditionals', category: 'Data Science', month: 'Month 1', completed: true, notes: '', order: 10 },
      { id: 'r11', title: 'Loops (for, while)', category: 'Data Science', month: 'Month 1', completed: true, notes: '', order: 11 },
      { id: 'r12', title: 'Functions', category: 'Data Science', month: 'Month 2', completed: false, notes: '', order: 12 },
      { id: 'r13', title: 'Lists & Tuples', category: 'Data Science', month: 'Month 2', completed: false, notes: '', order: 13 },
      { id: 'r14', title: 'Dictionaries', category: 'Data Science', month: 'Month 2', completed: false, notes: '', order: 14 },
      { id: 'r15', title: 'File Handling', category: 'Data Science', month: 'Month 2', completed: false, notes: '', order: 15 },
      { id: 'r16', title: 'NumPy', category: 'Data Science', month: 'Month 3', completed: false, notes: '', order: 16 },
      { id: 'r17', title: 'Pandas Basics', category: 'Data Science', month: 'Month 3', completed: false, notes: '', order: 17 },
      { id: 'r18', title: 'Percentages & Ratios', category: 'Mathematics', month: 'Month 1', completed: true, notes: '', order: 18 },
      { id: 'r19', title: 'Basic Algebra', category: 'Mathematics', month: 'Month 1', completed: true, notes: '', order: 19 },
      { id: 'r20', title: 'Mean, Median & Mode', category: 'Mathematics', month: 'Month 2', completed: true, notes: '', order: 20 },
      { id: 'r21', title: 'Standard Deviation', category: 'Mathematics', month: 'Month 2', completed: false, notes: '', order: 21 },
      { id: 'r22', title: 'Probability Basics', category: 'Mathematics', month: 'Month 3', completed: false, notes: '', order: 22 },
      { id: 'r23', title: 'Conditional Probability', category: 'Mathematics', month: 'Month 3', completed: false, notes: '', order: 23 },
    ],
    sessions: [
      { id: 'se1', date: d(0), subjectName: 'Python Fundamentals', duration: 2.5, notes: 'Covered functions and list comprehensions' },
      { id: 'se2', date: d(0), subjectName: 'IELTS Preparation', duration: 1, notes: 'Reading practice test 3' },
      { id: 'se3', date: d(1), subjectName: 'Artificial Intelligence', duration: 3, notes: 'Decision tree algorithms and entropy' },
      { id: 'se4', date: d(1), subjectName: 'NumPy & Pandas', duration: 1.5, notes: 'NumPy array operations' },
      { id: 'se5', date: d(2), subjectName: 'Statistics for Data Science', duration: 2, notes: 'Standard deviation and variance' },
      { id: 'se6', date: d(2), subjectName: 'MERN Backend', duration: 1.5, notes: 'JWT authentication implementation' },
      { id: 'se7', date: d(3), subjectName: 'Graph Theory', duration: 2, notes: 'Spanning trees and MST algorithms' },
      { id: 'se8', date: d(4), subjectName: 'Python Fundamentals', duration: 1.5, notes: 'OOP concepts and classes' },
      { id: 'se9', date: d(5), subjectName: 'Google Data Analytics Certificate', duration: 2, notes: 'Completed Course 2: Ask Questions to Make Decisions' },
      { id: 'se10', date: d(6), subjectName: 'IELTS Preparation', duration: 1.5, notes: 'Writing task 2 practice essay' },
    ],
    projects: [
      {
        id: 'p1',
        name: 'Movie Recommendation System',
        description: 'Content-based filtering recommendation engine using cosine similarity and TF-IDF vectorization',
        technologies: ['Python', 'Pandas', 'Scikit-learn', 'Flask', 'React'],
        githubLink: 'https://github.com/student/movie-recommender',
        progress: 65,
        status: 'in-progress',
      },
      {
        id: 'p2',
        name: 'Student Performance EDA Dashboard',
        description: 'Exploratory data analysis and visualization dashboard for academic performance prediction',
        technologies: ['Python', 'Matplotlib', 'Seaborn', 'Pandas', 'Streamlit'],
        githubLink: 'https://github.com/student/student-performance-analysis',
        progress: 85,
        status: 'in-progress',
      },
      {
        id: 'p3',
        name: 'COVID-19 Data Tracker',
        description: 'Real-time COVID-19 statistics tracker with interactive maps and trend analysis',
        technologies: ['React', 'TypeScript', 'Recharts', 'REST API'],
        githubLink: 'https://github.com/student/covid-tracker',
        progress: 100,
        status: 'completed',
      },
    ],
    germanyItems: [
      { id: 'g1', section: 'IELTS Preparation', task: 'Register for IELTS Academic exam', progress: 0, deadline: '2025-08-31', completed: false, notes: '' },
      { id: 'g2', section: 'IELTS Preparation', task: 'Complete 10+ reading practice tests', progress: 30, deadline: '2025-08-15', completed: false, notes: 'Completed 3 practice tests so far' },
      { id: 'g3', section: 'IELTS Preparation', task: 'Writing Task 1 — graphs and charts', progress: 25, deadline: '2025-08-15', completed: false, notes: '' },
      { id: 'g4', section: 'IELTS Preparation', task: 'Writing Task 2 — academic essays', progress: 20, deadline: '2025-08-15', completed: false, notes: '' },
      { id: 'g5', section: 'IELTS Preparation', task: 'Speaking mock sessions with tutor', progress: 10, deadline: '2025-08-20', completed: false, notes: '' },
      { id: 'g6', section: 'IELTS Preparation', task: 'Achieve IELTS Band 7.0+', progress: 0, deadline: '2025-09-15', completed: false, notes: '' },
      { id: 'g7', section: 'SOP Preparation', task: 'Research SOP structure for German universities', progress: 50, deadline: '2025-09-30', completed: false, notes: 'Reviewed 5 sample SOPs from TUM and LMU' },
      { id: 'g8', section: 'SOP Preparation', task: 'Draft SOP v1 (800–1000 words)', progress: 0, deadline: '2025-10-15', completed: false, notes: '' },
      { id: 'g9', section: 'SOP Preparation', task: 'Get SOP reviewed by professor/mentor', progress: 0, deadline: '2025-11-01', completed: false, notes: '' },
      { id: 'g10', section: 'SOP Preparation', task: 'Finalize SOP for all universities', progress: 0, deadline: '2025-11-30', completed: false, notes: '' },
      { id: 'g11', section: 'University Shortlisting', task: 'Research 20+ German universities for Data Science MSc', progress: 70, deadline: '2025-09-30', completed: false, notes: 'Researched TU Munich, LMU, RWTH Aachen, TU Berlin' },
      { id: 'g12', section: 'University Shortlisting', task: 'Shortlist top 8–10 universities', progress: 40, deadline: '2025-10-15', completed: false, notes: '' },
      { id: 'g13', section: 'University Shortlisting', task: 'Verify admission requirements and deadlines', progress: 50, deadline: '2025-10-31', completed: false, notes: '' },
      { id: 'g14', section: 'University Shortlisting', task: 'Submit applications to all shortlisted universities', progress: 0, deadline: '2025-12-15', completed: false, notes: '' },
      { id: 'g15', section: 'LOR Collection', task: 'Identify 3 professors/mentors for recommendation', progress: 60, deadline: '2025-09-15', completed: false, notes: 'Approached AI and DS professors' },
      { id: 'g16', section: 'LOR Collection', task: 'Send formal LOR request emails', progress: 30, deadline: '2025-10-01', completed: false, notes: '' },
      { id: 'g17', section: 'LOR Collection', task: 'Follow up and collect all LORs', progress: 0, deadline: '2025-11-15', completed: false, notes: '' },
      { id: 'g18', section: 'Projects', task: 'Complete 2 major data science projects for portfolio', progress: 65, deadline: '2025-11-30', completed: false, notes: 'Movie Recommender at 65%' },
      { id: 'g19', section: 'Projects', task: 'Document all projects with README and technical report', progress: 40, deadline: '2025-11-30', completed: false, notes: '' },
      { id: 'g20', section: 'Projects', task: 'Deploy at least 1 project publicly', progress: 20, deadline: '2025-12-01', completed: false, notes: '' },
      { id: 'g21', section: 'Certifications', task: 'Complete Google Data Analytics Professional Certificate', progress: 30, deadline: '2025-10-31', completed: false, notes: '2/8 courses done' },
      { id: 'g22', section: 'Certifications', task: 'Complete IBM Data Science Professional Certificate', progress: 10, deadline: '2025-11-30', completed: false, notes: '1/10 courses done' },
      { id: 'g23', section: 'Certifications', task: 'Python for Data Science — freeCodeCamp', progress: 70, deadline: '2025-08-31', completed: false, notes: '' },
    ],
  };
}
